modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL = "https://github.com/HungTeen/Immortal/issues"

[[mods]]
modId = "opentd"
version = "${file.jarVersion}"
displayName = "HungTeen's Open Tower Defence"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://space.bilibili.com/362855464"
logoFile = "examplemod.png"
credits = "..."
authors = "HungTeen, GrassCrap"
description = '''
A mod that providers stuffs to play tower defence in mincraft.
'''

[[dependencies.opentd]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opentd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opentd]]
modId = "htlib"
mandatory = true
versionRange = "[0.8,)"

[[dependencies.opentd]]
modId = "geckolib"
mandatory = true
versionRange = "[3.1.38,)"
