modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL = "https://github.com/HungTeen/Immortal/issues"

[[mods]]
modId = "opentd"
version = "${file.jarVersion}"
displayName = "HungTeen's Open Tower Defence"
updateJSONURL="https://github.com/HungTeen/HTMCMods/blob/main/opentd.json"
displayURL = "https://space.bilibili.com/362855464"
logoFile = "logo.png"
credits = "..."
authors = "HungTeen, GrassCrap"
description = '''
A mod that providers stuffs to play tower defence in minecraft.
'''

[[dependencies.opentd]]
modId = "forge"
mandatory = true
versionRange = "[43.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opentd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.opentd]]
modId = "htlib"
mandatory = true
versionRange = "[0.9.0,)"

[[dependencies.opentd]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.38,)"
